services:
  postgres:
    image: "postgres:18.0"
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gestioneleves
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=e2ce7969b6

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gestioneleves
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=e2ce7969b6

  adminer:
    image: "adminer:latest"
    ports:
      - "8081:8080"
    depends_on:
      - postgres